### ISSUE TITLE
The app crashes when clicking on the "COUNTING" feature

### ISSUE THREAD

**Issue by ahyar92** [wistein/TourCount#18] opened 2018-05-24 23:18 UTC
#### Expected behavior
Supposedly, when I click on the "Counting" feature, the feature works fine without error

#### Actual behavior
When I open the app and click on the "COUNTING" feature, the app suddenly crashes and exits by itself. And I have reinstalled, but the error persists.

#### How to reproduce
1. Install and open the app
2. Next click the feature "COUNTING"  located under the Prepare Recording feature. Or click the Counting icon located above the app next to the pencil icon.
*Then you will find the error as I experienced*

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 3.0.3

#### Recording Of The Bug
https://www.youtube.com/watch?v=kG74jxBP6t8

#### Logcat
```
05-25 05:42:28.915  3695  3695 E AndroidRuntime: FATAL EXCEPTION: main
05-25 05:42:28.915  3695  3695 E AndroidRuntime: Process: com.wmstein.tourcount, PID: 3695
05-25 05:42:28.915  3695  3695 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.wmstein.tourcount/com.wmstein.tourcount.CountingActivity}: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3136)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3167)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5527)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: Caused by: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.getProviderProperties(ILocationManager.java:1031)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.location.LocationManager.getProvider(LocationManager.java:373)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at com.wmstein.tourcount.CountingActivity.onResume(CountingActivity.java:268)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6379)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3125)
05-25 05:42:28.915  3695  3695 E AndroidRuntime: 	... 10 more
05-25 05:42:28.917  3695  3695 E MQSEventManagerDelegate: failed to get MQSService.
```

**Comment by wistein** [comment] 2018-08-03 22:43
Thanks for testing.
The crashes caused by permission handling should be fixed now with commit d167ec8.
Please test and close issue when ok.
After a week I will close the issue.

**Closed as completed** 2018-08-14 21:10 UTC
